import "./globals.css";
import { Roboto } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";

const roboto = Roboto({ weight: "300", subsets: ["latin"] });

export const metadata = {
  title: "Mood",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={roboto.className}>
          <main className="w-full flex items-center justify-center h-screen">
            {children}
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
